### PR TITLE
Add jsdoc

### PR DESCRIPTION
**Pull request by epszaw**
For more comfortable work :smile_cat:

### CODE REVIEW

**Review by jimmywarting — APPROVED** [review]

**Comment by matthewmueller** [comment]
awesome!

**Comment by epszaw** [comment]
@matthewmueller, omg, since 2 years you finally merge this! 🎉 😄

**Comment by matthewmueller** [comment]
this change required 2 years of careful, line-by-line review 🙃

**Comment by epszaw** [comment]
😂

**Pull request merged**
